### ISSUE TITLE
请问直接运行该项目得到的结果不太对的原因

### ISSUE THREAD

**Issue by Recope** [ceej7/DX12-HybridPipeline#1]
我尝试学习一下你的混合管线写法，运行项目发现没有阴影和反射，是需要调一些参数吗？
![2021-04-24_155927](https://user-images.githubusercontent.com/41226982/115952013-665a7580-a516-11eb-8a5f-695f60186ef4.png)

**Comment by Recope** [comment]
好像是enableraytracing没开，我开了之后，好像还得修改device和commandlist的版本，但是还是报异常，大佬能给点指示吗？

**Comment by ceej7** [comment]
回到commit 6c6783eb7bb4fde10e203a786043e0319e45f27a，我后续实验了新功能所以把rt相关的干掉了

**Comment by whaleeej** [comment]
> 好像是enableraytracing没开，我开了之后，好像还得修改device和commandlist的版本，但是还是报异常，大佬能给点指示吗？

我改出来了一个dev分支，你看这个分支的内容吧

**Comment by Recope** [comment]
大佬，我启动项目后，发现窗口没有加载出来画面，是不是与HDR文件的要求有关？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ceej7/DX12-HybridPipeline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1)





 
Closed #1.

**Comment by whaleeej** [comment]
> 大佬，我启动项目后，发现窗口没有加载出来画面，是不是与HDR文件的要求有关？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ceej7/DX12-HybridPipeline" ***@***.***&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 中午1:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

dev分支下已经传了的~

**Comment by Recope** [comment]
谢谢大佬不吝赐教！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ceej7/DX12-HybridPipeline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1)





  
好像是enableraytracing没开，我开了之后，好像还得修改device和commandlist的版本，但是还是报异常，大佬能给点指示吗？
  
我改出来了一个dev分支，你看这个分支的内容吧

**Comment by Recope** [comment]
大佬，我现在已经参考你的程序做到BFMR了，但是我直接参考你的shader做出来的效果不对，我感觉可能是预设的一些宏可能需要适配不同的程序，我说的是下图的这些：


请问这里需要更改吗？希望您有空能够解答一下，十分感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ceej7/DX12-HybridPipeline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 中午1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1)





  
大佬，我启动项目后，发现窗口没有加载出来画面，是不是与HDR文件的要求有关？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ceej7/DX12-HybridPipeline" @.&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 中午1:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
dev分支下已经传了的~

**Comment by whaleeej** [comment]
> 大佬，我现在已经参考你的程序做到BFMR了，但是我直接参考你的shader做出来的效果不对，我感觉可能是预设的一些宏可能需要适配不同的程序，我说的是下图的这些： 请问这里需要更改吗？希望您有空能够解答一下，十分感谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ceej7/DX12-HybridPipeline" ***@***.***&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 中午1:34 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 大佬，我启动项目后，发现窗口没有加载出来画面，是不是与HDR文件的要求有关？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ceej7/DX12-HybridPipeline" @.&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 中午1:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. dev分支下已经传了的~ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

bmdr建议直接参考论文源码，我这里首先有一些魔改，其次本身pt的地方原来也写的不太对。这部分参考我写的反而会让你写错

**Comment by Recope** [comment]
大佬，我查看你的raytracing.hlsl的时候发现一个问题，有点不解，希望你能帮忙解答一下，就是计算间接光照时最后所除的pdf是怎么计算的？

这与EPIC重要性采样计算的pdf不一样，


而且我得到的结果在经过BMFR后，有一些地方会出现莫名其妙的高光，经过滤波后，会导致黑色伪影扩散至周边，这是哪里的问题导致的？



希望您有空能够回复一下，十分感谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zwhy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 下午3:03
***@***.***&gt;;

主题:&nbsp;回复： [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1)



谢谢大佬不吝赐教！




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ceej7/DX12-HybridPipeline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1)





  
好像是enableraytracing没开，我开了之后，好像还得修改device和commandlist的版本，但是还是报异常，大佬能给点指示吗？
  
我改出来了一个dev分支，你看这个分支的内容吧

**Comment by whaleeej** [comment]
> 大佬，我查看你的raytracing.hlsl的时候发现一个问题，有点不解，希望你能帮忙解答一下，就是计算间接光照时最后所除的pdf是怎么计算的？ 这与EPIC重要性采样计算的pdf不一样， 而且我得到的结果在经过BMFR后，有一些地方会出现莫名其妙的高光，经过滤波后，会导致黑色伪影扩散至周边，这是哪里的问题导致的？ 希望您有空能够回复一下，十分感谢！ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zwhy" ***@***.***&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 下午3:03 ***@***.***&gt;; 主题:&nbsp;回复： [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 谢谢大佬不吝赐教！
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "ceej7/DX12-HybridPipeline" ***@***.***&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 中午1:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 好像是enableraytracing没开，我开了之后，好像还得修改device和commandlist的版本，但是还是报异常，大佬能给点指示吗？ 我改出来了一个dev分支，你看这个分支的内容吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

上一个reply我就提到我pt写错了，错的地方就主要就在于这个pdf当时是没参考任何东西手推的，虽然过程已经找不到了但我trace出来的结果看起来不太对，特别是高亮的位置，所以我强行做了一个clamp。我自己的private仓库已经该成ue那种按照NDF去做重要性采样了

**Comment by Recope** [comment]
可以参考一下吗，有点头大，改了好久没改出来。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 晚上7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1)





  
大佬，我查看你的raytracing.hlsl的时候发现一个问题，有点不解，希望你能帮忙解答一下，就是计算间接光照时最后所除的pdf是怎么计算的？ 这与EPIC重要性采样计算的pdf不一样， 而且我得到的结果在经过BMFR后，有一些地方会出现莫名其妙的高光，经过滤波后，会导致黑色伪影扩散至周边，这是哪里的问题导致的？ 希望您有空能够回复一下，十分感谢！ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zwhy" @.&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 下午3:03 @.&gt;; 主题:&nbsp;回复： [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 谢谢大佬不吝赐教！
 …
 ------------------ 原始邮件 ------------------ 发件人: "ceej7/DX12-HybridPipeline" @.&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 中午1:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 好像是enableraytracing没开，我开了之后，好像还得修改device和commandlist的版本，但是还是报异常，大佬能给点指示吗？ 我改出来了一个dev分支，你看这个分支的内容吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
上一个reply我就提到我pt写错了，错的地方就主要就在于这个pdf当时是没参考任何东西手推的，虽然过程已经找不到了但我trace出来的结果看起来不太对，特别是高亮的位置，所以我强行做了一个clamp。我自己的private仓库已经该成ue那种按照NDF去做重要性采样了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Recope** [comment]
我把pdf改成epic的pdf，还是会出现一些这种ghost，但是高光的地方确实改善了：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ceej7/DX12-HybridPipeline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1)





  
大佬，我查看你的raytracing.hlsl的时候发现一个问题，有点不解，希望你能帮忙解答一下，就是计算间接光照时最后所除的pdf是怎么计算的？ 这与EPIC重要性采样计算的pdf不一样， 而且我得到的结果在经过BMFR后，有一些地方会出现莫名其妙的高光，经过滤波后，会导致黑色伪影扩散至周边，这是哪里的问题导致的？ 希望您有空能够回复一下，十分感谢！ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zwhy" @.&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 下午3:03 @.&gt;; 主题:&nbsp;回复： [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 谢谢大佬不吝赐教！
 …
 ------------------ 原始邮件 ------------------ 发件人: "ceej7/DX12-HybridPipeline" @.&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 中午1:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 好像是enableraytracing没开，我开了之后，好像还得修改device和commandlist的版本，但是还是报异常，大佬能给点指示吗？ 我改出来了一个dev分支，你看这个分支的内容吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
上一个reply我就提到我pt写错了，错的地方就主要就在于这个pdf当时是没参考任何东西手推的，虽然过程已经找不到了但我trace出来的结果看起来不太对，特别是高亮的位置，所以我强行做了一个clamp。我自己的private仓库已经该成ue那种按照NDF去做重要性采样了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Recope** [comment]
大佬，我把raytracing做间接光的那部分改成按照ue4的那种按照NDF做重要性采样的方法了，但是得出的反射的结果会变得很暗是什么原因呢？我计算的pdf如下图所示，您能帮忙看看是否有问题吗？









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ceej7/DX12-HybridPipeline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1)





  
大佬，我查看你的raytracing.hlsl的时候发现一个问题，有点不解，希望你能帮忙解答一下，就是计算间接光照时最后所除的pdf是怎么计算的？ 这与EPIC重要性采样计算的pdf不一样， 而且我得到的结果在经过BMFR后，有一些地方会出现莫名其妙的高光，经过滤波后，会导致黑色伪影扩散至周边，这是哪里的问题导致的？ 希望您有空能够回复一下，十分感谢！ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zwhy" @.&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 下午3:03 @.&gt;; 主题:&nbsp;回复： [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 谢谢大佬不吝赐教！
 …
 ------------------ 原始邮件 ------------------ 发件人: "ceej7/DX12-HybridPipeline" @.&gt;; 发送时间:&nbsp;2021年4月26日(星期一) 中午1:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ceej7/DX12-HybridPipeline] 请问直接运行该项目得到的结果不太对的原因 (#1) 好像是enableraytracing没开，我开了之后，好像还得修改device和commandlist的版本，但是还是报异常，大佬能给点指示吗？ 我改出来了一个dev分支，你看这个分支的内容吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
上一个reply我就提到我pt写错了，错的地方就主要就在于这个pdf当时是没参考任何东西手推的，虽然过程已经找不到了但我trace出来的结果看起来不太对，特别是高亮的位置，所以我强行做了一个clamp。我自己的private仓库已经该成ue那种按照NDF去做重要性采样了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
